// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/osije/ai-os/app/toolservice/internal/conf"
	"github.com/osije/ai-os/app/toolservice/internal/server"
	"github.com/osije/ai-os/app/toolservice/internal/service"
)

// Injectors from wire.go:

func initApp() (*kratos.App, error) {
	config := conf.Load()
	toolServiceImpl := service.NewToolServiceImpl(config)
	grpcServer := server.NewGRPCServer(config, toolServiceImpl)
	app := newApp(grpcServer)
	return app, nil
}
