// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/osije/ai-os/app/gateway/internal/conf"
	"github.com/osije/ai-os/app/gateway/internal/server"
	"github.com/osije/ai-os/app/gateway/internal/service"
)

// Injectors from wire.go:

func initApp() (*kratos.App, error) {
	config := conf.Load()
	gatewayServiceImpl := service.NewGatewayServiceImpl(config)
	httpServer := server.NewHTTPServer(config, gatewayServiceImpl)
	app := newApp(httpServer)
	return app, nil
}
