// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/osije/ai-os/app/tracestore/internal/conf"
	"github.com/osije/ai-os/app/tracestore/internal/server"
	"github.com/osije/ai-os/app/tracestore/internal/service"
)

// Injectors from wire.go:

func initApp() (*kratos.App, error) {
	config := conf.Load()
	traceStoreServiceImpl, err := service.NewTraceStoreServiceImpl(config)
	if err != nil {
		return nil, err
	}
	grpcServer := server.NewGRPCServer(config, traceStoreServiceImpl)
	app := newApp(grpcServer)
	return app, nil
}
