// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/osije/ai-os/app/orchestrator/internal/conf"
	"github.com/osije/ai-os/app/orchestrator/internal/metrics"
	"github.com/osije/ai-os/app/orchestrator/internal/server"
	"github.com/osije/ai-os/app/orchestrator/internal/service"
)

// Injectors from wire.go:

func initApp() (*kratos.App, error) {
	config := conf.Load()
	metricsMetrics := metrics.New()
	orchestratorServiceImpl := service.NewOrchestratorServiceImpl(config, metricsMetrics)
	grpcServer := server.NewGRPCServer(config, orchestratorServiceImpl)
	app := newApp(config, grpcServer, metricsMetrics)
	return app, nil
}
